### ISSUE TITLE
No OSX py 36 build

### ISSUE THREAD

**Issue by stuertz** [conda-forge/parse_type-feedstock#2]
The generated .travis.yml does not include a py36 build. The comment says that I should have a look at conda-forge.yml and/or the recipe/meta.yaml. But I don't have a clue why conda smithy thinks this is excluded.
Could anyone give me a hint?

**Comment by ocefpaf** [comment]
`enum34` is not present for `Python 3.6`, and as far as I know you don't really need it for Python 3, right?

If you add a pre-selector there `enum34 # [not py36]` and re-rerender everything should work.

**Comment by stuertz** [comment]
Uhh. OK. That sounds reasonable. Thank you.
